[git]

[git.config]
email = "semverbot@github.com"
name = "semverbot"

[git.tags]
prefix = ""

[semver]
mode = "auto"

[semver.detection]
patch = ["fix/", "[fix]"]
minor = ["feature/", "[feature]"]
major = ["release/", "[release]"]
