name: development

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    name: pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up executables path
        run: |
          echo "$(pwd)"
          ls -al
          mkdir bin
          cd bin
          echo "$(pwd)" >> $GITHUB_PATH
          echo "$PATH"

      - name: set up semverbot
        run: |
          cd bin
          curl -o sbot -L https://github.com/restechnica/semverbot/releases/download/v1.0.0/sbot-linux-amd64
          chmod +x sbot
          echo "$(pwd)"
          ls -al

      - name: test
        run: |
          sbot update version

