name: main

on:
  push:
    branches: [ main ]

env:
  SEMVERBOT_VERSION: "0.0.4"

jobs:
  build:
    name: pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up executables path
        run: |
          mkdir bin
          cd bin
          echo "$(pwd)" >> $GITHUB_PATH

      - name: set up semverbot
        run: |
          cd bin
          curl -o sbot -L https://github.com/restechnica/semverbot/releases/download/v$SEMVERBOT_VERSION/sbot-linux-amd64
          chmod +x sbot

      - name: release
        run: |
          sbot update version

          echo "current version: $(sbot get version)"
          echo "next version: $(sbot predict version)"

          sbot release version
          git push origin v$(sbot get version)

